module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
        colors: {
            'dark-background-main': 'hsl(222, 26%, 31%)',
            'dark-background-keyboard': 'hsl(223, 31%, 20%)',
            'dark-background-screen': 'hsl(224, 36%, 15%)',
            'dark-key-blue-background': 'hsl(225, 21%, 49%)',
            'dark-key-blue-shadow': 'hsl(224, 28%, 35%)',
            'dark-key-red-background': 'hsl(6, 63%, 50%)',
            'dark-key-red-shadow': 'hsl(6, 70%, 34%)',
            'dark-key-orange-background': 'hsl(30, 25%, 89%)',
            'dark-key-orange-shadow': 'hsl(28, 16%, 65%)',
            'dark-text-blue': 'hsl(221, 14%, 31%)',
            'light-background-main': 'hsl(0, 0%, 90%)',
            'light-background-keyboard': 'hsl(0, 5%, 81%)',
            'light-background-screen': 'hsl(0, 0%, 93%)',
            'light-key-cyan-background': 'hsl(185, 42%, 37%)',
            'light-key-cyan-shadow': 'hsl(185, 58%, 25%)',
            'light-key-orange-background': 'hsl(25, 98%, 40%)',
            'light-key-orange-shadow': 'hsl(25, 99%, 27%)',
            'light-key-yellow-background': 'hsl(45, 7%, 89%)',
            'light-key-yellow-shadow': 'hsl(35, 11%, 61%',
            'light-text-blue': 'hsl(60, 10%, 19%)',
            'violet-background-main': 'hsl(268, 75%, 9%)',
            'violet-background-secondary': 'hsl(268, 71%, 12%)',
            'violet-key-violet-background': 'hsl(281, 89%, 26%)',
            'violet-key-magenta-shadow': 'hsl(285, 91%, 52%)',
            'violet-key-cyan-background': 'hsl(176, 100%, 44%)',
            'violet-key-cyan-shadow': 'hsl(177, 92%, 70%)',
            'violet-key-dark-violet-background': 'hsl(268, 47%, 21%)',
            'violet-key-dark-magenta-shadow': 'hsl(290, 70%, 36%',
            'violet-text-yellow': 'hsl(52, 100%, 62%)',
            'violet-text-blue': 'hsl(198, 20%, 13%)',
        }
    },
  },
  plugins: [],
}